"""serivs_etkisi eklendi

Revision ID: 05b48e04ce5f
Revises: 08066cbaeb1a
Create Date: 2025-05-23 13:04:47.206668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b48e04ce5f'
down_revision = '08066cbaeb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiber_ariza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serivs_etkisi', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiber_ariza', schema=None) as batch_op:
        batch_op.drop_column('serivs_etkisi')

    # ### end Alembic commands ###
