"""ilk tablo

Revision ID: 08066cbaeb1a
Revises: 
Create Date: 2025-05-23 13:03:44.705999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08066cbaeb1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiber_ariza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hafta', sa.String(length=10), nullable=True),
    sa.Column('bolge', sa.String(length=50), nullable=True),
    sa.Column('bulten_no', sa.String(length=20), nullable=False),
    sa.Column('il', sa.String(length=50), nullable=True),
    sa.Column('guzergah', sa.String(length=200), nullable=True),
    sa.Column('lokasyon', sa.String(length=100), nullable=True),
    sa.Column('ariza_baslangic', sa.DateTime(), nullable=True),
    sa.Column('ariza_bitis', sa.DateTime(), nullable=True),
    sa.Column('ariza_konsolide', sa.String(length=200), nullable=True),
    sa.Column('ariza_kok_neden', sa.String(length=200), nullable=True),
    sa.Column('hags_asildi_mi', sa.String(length=10), nullable=True),
    sa.Column('refakat_durumu', sa.String(length=10), nullable=True),
    sa.Column('servis_etkisi', sa.String(length=10), nullable=True),
    sa.Column('ariza_suresi', sa.String(length=10), nullable=True),
    sa.Column('kordinat_a', sa.String(length=50), nullable=True),
    sa.Column('kordinat_b', sa.String(length=50), nullable=True),
    sa.Column('kablo_tipi', sa.String(length=50), nullable=True),
    sa.Column('hags_suresi', sa.String(length=20), nullable=True),
    sa.Column('kesinti_suresi', sa.String(length=20), nullable=True),
    sa.Column('kalici_cozum', sa.String(length=10), nullable=True),
    sa.Column('kullanilan_malzeme', sa.String(length=200), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bulten_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fiber_ariza')
    # ### end Alembic commands ###
