"""Add DeplaseIslah table

Revision ID: 285364aa2f6e
Revises: 05b48e04ce5f
Create Date: 2025-06-19 21:59:04.032394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285364aa2f6e'
down_revision = '05b48e04ce5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deplase_islah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yil', sa.String(length=10), nullable=True),
    sa.Column('hafta', sa.String(length=10), nullable=True),
    sa.Column('ddo', sa.String(length=100), nullable=True),
    sa.Column('guzergah', sa.String(length=200), nullable=True),
    sa.Column('is_tipi', sa.String(length=50), nullable=True),
    sa.Column('kordinat_a', sa.String(length=50), nullable=True),
    sa.Column('kordinat_b', sa.String(length=50), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deplase_islah')
    # ### end Alembic commands ###
