"""Add DeplaseIslah and HasarTazmin tables

Revision ID: 72049cfd249a
Revises: 285364aa2f6e
Create Date: 2025-06-19 22:11:08.641848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72049cfd249a'
down_revision = '285364aa2f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasar_tazmin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bolge', sa.String(length=100), nullable=True),
    sa.Column('yazi_no', sa.String(length=100), nullable=True),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('asil_firma', sa.String(length=200), nullable=True),
    sa.Column('muhaberat_verilis_tarihi', sa.DateTime(), nullable=True),
    sa.Column('taseron', sa.String(length=200), nullable=True),
    sa.Column('durumu', sa.String(length=50), nullable=True),
    sa.Column('muhaberat_teslim_eden', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hasar_tazmin')
    # ### end Alembic commands ###
