"""Add all new tables: DeplaseIslah, HasarTazmin, FTTBOptimizasyon, KritikModernizasyon

Revision ID: 82bbb423f4cc
Revises: adc38353a02e
Create Date: 2025-06-20 07:33:21.753084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bbb423f4cc'
down_revision = 'adc38353a02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kritik_modernizasyon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yil', sa.String(length=10), nullable=True),
    sa.Column('hafta', sa.String(length=10), nullable=True),
    sa.Column('ddo', sa.String(length=100), nullable=True),
    sa.Column('bulten_no', sa.String(length=100), nullable=True),
    sa.Column('lokasyon_id', sa.String(length=100), nullable=True),
    sa.Column('is_tipi', sa.String(length=200), nullable=True),
    sa.Column('lokasyon', sa.String(length=200), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('durumu', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kritik_modernizasyon')
    # ### end Alembic commands ###
