"""Add DeplaseIslah, HasarTazmin and FTTBOptimizasyon tables

Revision ID: adc38353a02e
Revises: 72049cfd249a
Create Date: 2025-06-20 07:24:57.051906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc38353a02e'
down_revision = '72049cfd249a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fttb_optimizasyon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yil', sa.String(length=10), nullable=True),
    sa.Column('hafta', sa.String(length=10), nullable=True),
    sa.Column('ddo', sa.String(length=100), nullable=True),
    sa.Column('statu', sa.String(length=100), nullable=True),
    sa.Column('obek', sa.String(length=100), nullable=True),
    sa.Column('fttb_ring_name', sa.String(length=200), nullable=True),
    sa.Column('lokasyon_id', sa.String(length=100), nullable=True),
    sa.Column('ci_name', sa.String(length=200), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fttb_optimizasyon')
    # ### end Alembic commands ###
