"""Add pinned and manual ID features

Revision ID: ded6fccbfd38
Revises: e933692d4e5a
Create Date: 2025-06-25 18:32:19.500541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded6fccbfd38'
down_revision = 'e933692d4e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playground_module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('menu_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playground_module', schema=None) as batch_op:
        batch_op.drop_column('menu_order')
        batch_op.drop_column('is_pinned')

    # ### end Alembic commands ###
