"""Add missing fields to FiberAriza

Revision ID: facac0002f6b
Revises: 82bbb423f4cc
Create Date: 2025-06-24 08:58:15.381408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'facac0002f6b'
down_revision = '82bbb423f4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiber_ariza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refakat_saglandi_mi', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('deplase_islah_ihtiyaci', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('hasar_tazmin_sureci', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('otdr_olcum_bilgileri', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('etkilenen_servis_bilgileri', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('yil', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiber_ariza', schema=None) as batch_op:
        batch_op.drop_column('yil')
        batch_op.drop_column('etkilenen_servis_bilgileri')
        batch_op.drop_column('otdr_olcum_bilgileri')
        batch_op.drop_column('hasar_tazmin_sureci')
        batch_op.drop_column('deplase_islah_ihtiyaci')
        batch_op.drop_column('refakat_saglandi_mi')

    # ### end Alembic commands ###
